// <auto-generated />
namespace OfficeManager.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSex));
        
        string IMigrationMetadata.Id
        {
            get { return "201309121443009_AddSex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
